import { ArrowLeftIcon } from '@heroicons/react/outline'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import { AnimatePresence,motion } from 'framer-motion'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import CommentModal from '../../components/CommentModal'
import Post from '../../components/Post'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import { db } from '../../firebase'

const PostPage = ({ newsResults, randomUsersResults }) => {


 const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState();
  const [comments, setComments] = useState([]);

  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [id]
  );

  // get comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [id]);
    
  return (
    <div>
    <Head>
      <title>Post Page</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex min-h-screen mx-auto">
      {/* Sidebar */}
      <Sidebar />

      {/* Feed */}

      <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
        <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
          <div className="hoverEffect" onClick={() => router.push("/")}>
            <ArrowLeftIcon className="h-5 " />
          </div>
          <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
            Tweet
          </h2>
        </div>

        <Post id={id} post={post} />
        {comments.length > 0 && (
          <div className="">
            <AnimatePresence>
              {comments.map((comment) => (
                <motion.div
                  key={comment.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 1 }}
                >
                
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </div>

      {/* Widgets */}

      <Widgets
        newsResults={newsResults.articles}
        randomUsersResults={randomUsersResults.results}
      />

      {/* Modal */}

      <CommentModal />
    </main>
  </div>
  )
}
export async function getServerSideProps() {
    const newsResults = await fetch(
      "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    ).then((res) => res.json());
  
    // Who to follow section
  
    let randomUsersResults = [];
  
    try {
      const res = await fetch(
        "https://randomuser.me/api/?results=30&inc=name,login,picture"
      );
  
      randomUsersResults = await res.json();
    } catch (e) {
      randomUsersResults = [];
    }
  
    return {
      props: {
        newsResults,
        randomUsersResults,
      },
    };
  }

export default PostPage